apiVersion: v1
kind: Service
metadata:
  namespace: ctse
  name: user-management-service
spec:
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
  publishNotReadyAddresses: true
